const actions = {
  GET_URL_LIST: "GET_URL_LIST",
  PUT_URL_LIST: "PUT_URL_LIST",
  POST_NEW_URL: "POST_NEW_URL",
  POST_NEW_URL_SUCCESS: "POST_NEW_URL_SUCCESS",
  POST_NEW_URL_FAIL: "POST_NEW_URL_FAIL",
  POST_NEW_URL_REFRESH: "POST_NEW_URL_REFRESH",
  GET_URL: "GET_URL",
  PUT_URL: "PUT_URL",
};
export default actions;
