variable "ecs_target_group_b" {}
variable "ecs_subnet_a" {}
variable "ecs_subnet_b" {}
variable "ecs_subnet_c" {}
variable "ecs_sg" {}
variable "ecs_role" {}
variable "backend_ecr" {}
variable "aws_rds_cluster_name" {}
variable "ecs_target_group_a" {}
variable "aws_rds_cluster_host" {}
variable "aws_rds_cluster_ro_host" {}
variable "backend_sub_domain_prefix" {}
variable "domain_name" {}
variable "aws_secret_manager_secret_arn" {}